// Generated by CoffeeScript 1.6.3
(function() {
  var modc;

  modc = require('modc');

  module.exports.get = function() {
    return modc.get();
  };

  module.exports.set = function(newValue) {
    return modc.set(newValue);
  };

}).call(this);
